Potential solution for #134
MatterOverdrive/MatterOverdrive-Legacy-Edition pull request #135
Opened 2018-05-18 19:12 UTC by Lazarix

Potential solution for #134 
If i'm missing other changes because of moving tritanium_ingot.json to tritanium_ingot_nugget.json, let me know

2018-05-18 19:38 UTC, TheCodedOne commented
Have you actually checked that this works because looking at your "fix" i can see there's a 100% chance that it does not work

2018-05-18 20:48 UTC, ChloeDawn requested changes

2018-05-18 20:48 UTC, InsomniaKitten commented on src/main/resources/assets/matteroverdrive/recipes/tritanium_ingot.json
>      "item": "matteroverdrive:tritanium_ingot"
This recipe only outputs 1 ingot.

2018-05-18 20:48 UTC, InsomniaKitten commented on src/main/resources/assets/matteroverdrive/recipes/tritanium_ingot.json
> +            "ore": "matteroverdrive:tritanium_block"
This is not a valid ore name.

2018-05-19 23:05 UTC, Lazarix commented
well, an effort was made.

2018-05-19 23:17 UTC, closed without merging